// <auto-generated />
namespace mvc12122024.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class c : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(c));
        
        string IMigrationMetadata.Id
        {
            get { return "202412160419493_c"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
